#Histogram
par(mfrow=c(1,1))
hist(Parameter_N1$ELEVASI, breaks="Sturges", col="steelblue", main ="Histogram Raster Elevasi")
hist(Parameter_N1$SLOPE, breaks="Sturges", col="steelblue", main ="Histogram Raster Slope")
hist(Parameter_N1$CH, breaks="Sturges", col="steelblue", main ="Histogram Raster Curah Hujan")
#hist(Parameter_N1$CURVATURE, breaks="Sturges", col="steelblue", main ="Histogram Raster Curvature")
hist(Parameter_N1$JTS, breaks="Sturges", col="steelblue", main ="Histogram Raster Jarak Terhadap Sungai")
hist(Parameter_N1$TL, breaks="Sturges", col="steelblue", main ="Histogram Raster Tutupan Lahan")
hist(Parameter_N1$LD, breaks="Sturges", col="steelblue", main ="Histogram Raster Drainage Density")
hist(Parameter_N1$MANNNING, breaks="Sturges", col="steelblue", main ="Histogram Raster Manning Roughness Coefficient")
hist(Parameter_N1$TWI, breaks="Sturges", col="steelblue", main ="Histogram Raster TWI")
hist(Parameter_N1$JT, breaks="Sturges", col="steelblue", main ="Histogram Raster Jenis Tanah")
#hist(Parameter_N1$NDVI, breaks="Sturges", col="steelblue", main ="Histogram Raster NDVI")
hist(Parameter_N1$NDBI, breaks="Sturges", col="steelblue", main ="Histogram Raster NDBI")
hist(Parameter_N1$B5, breaks="Sturges", col="steelblue", main ="Histogram Raster Band Near InfraRed")